# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://petertwigg.com'
baseurl: ''
title: 'Peter Twigg'
description: 'Peter Twigg'
permalink: pretty
logo: "https://s.gravatar.com/avatar/e93642b3913fe528117101c28451d28b?s=80"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  My Meditation Channel: /my_meditation_channel/
  Sessions: /sessions/
  Testimonials: /testimonials/
  Blog: /blog/
  Contact: /contact/

# Footer nav
navigation_footer:
  Back to top: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text:
    feature_image: "https://picsum.photos/2560/600?image=976"
