# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://petertwigg.com'
baseurl: ''
title: 'Peter Twigg'
description: 'Peter Twigg'
permalink: pretty
logo: "https://s.gravatar.com/avatar/e93642b3913fe528117101c28451d28b?s=80"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Meditation
  url: /meditation/
- title: Events
  url: /Events/
- title: Sessions
  url: /sessions/
- title: Testimonials
  url: /testimonials/
- title: Contact
  url: /contact/
#- title: Blog
#  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=976"
