# Set theme
remote_theme: daviddarnes/alembic 

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://petertwigg.com'
baseurl: ''
title: 'Peter Twigg'
description: 'Tips, techniques & context to help you improve your meditation experience. Meditation courses for groups and individuals. One-on-one transformative sessions and counselling.'
permalink: pretty
logo: "https://s.gravatar.com/avatar/e93642b3913fe528117101c28451d28b?s=80"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Blog
  url: /blog/
- title: My Meditation Channel
  url: /my-meditation-channel/
- title: Courses
  url: /courses/
- title: Events
  url: /events/
- title: Corporate Events
  url: corporate 
- title: Sessions
  url: /sessions/
- title: Testimonials
  url: /testimonials/
- title: Contact
  url: /contact/


# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "Tips, Techniques & Context to Improve your Meditation"
    feature_text: 
    feature_image: "/images/banner-main-01-1600.jpg"

# Appears in sidebar. Set the urls then uncomment and comment out as desired
social_links: 
  Facebook: https://www.facebook.com/mymeditationchannel
  YouTube: https://www.youtube.com/channel/UC8Ik2FYO2lu71QjNKxUW-qw
  Twitter: https://twitter.com/solon_1
  LinkedIn: https://www.linkedin.com/in/peter-twigg-991a8818b/
  Instagram: https://www.instagram.com/peter_twigg_meditation/
  Patreon: https://www.patreon.com/bePatron?u=23503895 
  RSS: /feed.xml
  


# Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
sharing_links: 
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true
 
