source "https://rubygems.org"

gem "jekyll", "~> 3.9"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-mentions", "~> 1.5"
gem "jekyll-paginate", "~> 1.1"
gem "jekyll-seo-tag", "~> 2.6"
gem "jekyll-redirect-from", "~> 0.15"
gem "jekyll-default-layout", "~> 0.1"
gem "jekyll-feed", "~> 0.13"
gem "jemoji", "~> 0.11"
gem "jekyll-remote-theme", "~> 0.4"
gem "kramdown-parser-gfm",	"~> 1.1"
